import React,{useEffect,useState} from 'react';
import {Sparkles,Calendar,ArrowRight,Instagram,Flower2} from 'lucide-react';
import {GreenlantersLogo} from './GreenlantersLogo';
import {apiService} from '../data/api';
type PublicService={id:string;name:string;description?:string;active?:number|boolean;sortOrder?:number;price?:number};
type GalleryItem={id:string;photoBase64?:string;title?:string;caption?:string};
export const HomeViewV2:React.FC<{setActiveTab:(tab:string)=>void}>=({setActiveTab})=>{
 const[services,setServices]=useState<PublicService[]>([]);const[gallery,setGallery]=useState<GalleryItem[]>([]);const[loading,setLoading]=useState(true);
 useEffect(()=>{let cancelled=false;Promise.all([apiService.getServices(),apiService.getGallery()]).then(([s,g])=>{if(cancelled)return;setServices((Array.isArray(s)?s:[]).filter((x:PublicService)=>x.active!==0&&x.active!==false).sort((a,b)=>(a.sortOrder??999)-(b.sortOrder??999)));setGallery(Array.isArray(g)?g.filter((x:GalleryItem)=>Boolean(x.photoBase64)):[])}).catch(()=>{}).finally(()=>{if(!cancelled)setLoading(false)});return()=>{cancelled=true}},[]);
 return <div className="min-h-screen bg-[#F7F0E8] text-[#201D1A]">
  <section className="relative overflow-hidden bg-[#244536] text-white px-5 py-16 sm:py-24"><div className="absolute -right-24 -top-24 h-80 w-80 rounded-full bg-[#D98B73]/20 blur-3xl"/><div className="absolute -left-24 bottom-0 h-72 w-72 rounded-full bg-[#D8A62A]/10 blur-3xl"/><div className="relative z-10 max-w-6xl mx-auto grid lg:grid-cols-[1.1fr_.9fr] gap-12 items-center"><div className="space-y-7"><p className="text-[#F2C6B5] text-xs font-bold uppercase tracking-[.24em]">BettyJaimez Blanco · Nail Studio</p><h1 className="font-display text-4xl sm:text-6xl lg:text-7xl font-bold leading-[1.05]">Belleza que <span className="text-[#F2C6B5]">florece.</span></h1><p className="max-w-2xl text-base sm:text-lg text-white/80 leading-relaxed">Manicura, diseño y cuidado de uñas con una inspiración floral que recuerda a Medellín, sus montañas y sus colores.</p><div className="flex flex-col sm:flex-row gap-3"><button onClick={()=>setActiveTab('booking')} className="px-7 py-4 bg-[#F2C6B5] text-[#244536] font-bold text-xs uppercase tracking-widest rounded-lg hover:bg-white transition-colors flex items-center justify-center gap-2"><Calendar className="w-4 h-4"/>Reservar cita</button><a href="https://www.instagram.com/bettyjaimezblanco/" target="_blank" rel="noreferrer" className="px-7 py-4 border border-[#F2C6B5]/70 text-white font-bold text-xs uppercase tracking-widest rounded-lg hover:bg-white/5 transition-colors flex items-center justify-center gap-2"><Instagram className="w-4 h-4 text-[#F2C6B5]"/>Instagram</a></div></div><div className="flex justify-center lg:justify-end"><div className="bjb-glow rounded-full"><GreenlantersLogo size={310}/></div></div></div></section>
  <section className="max-w-6xl mx-auto px-5 py-16 sm:py-20"><div className="max-w-2xl mb-10"><p className="text-[#B96D59] text-xs font-bold uppercase tracking-[.2em]">Servicios</p><h2 className="font-display text-3xl sm:text-4xl font-bold text-[#244536] mt-2">Tus manos, tu estilo</h2><p className="text-[#756C65] mt-3">Precios iniciales orientativos. Betty podrá modificarlos desde la zona de gestión.</p></div>{loading?<p className="text-sm text-[#756C65]">Cargando…</p>:services.length===0?<div className="bg-white border border-[#D98B73]/25 rounded-xl p-7 text-[#756C65]">Los servicios se configurarán próximamente.</div>:<div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-5">{services.map(s=><article key={s.id} className="bg-white border border-[#D98B73]/25 border-t-4 border-t-[#D98B73] p-6 rounded-xl shadow-sm hover:-translate-y-1 transition-all"><Sparkles className="w-6 h-6 text-[#D8A62A] mb-5"/><h3 className="font-display text-xl font-bold text-[#244536]">{s.name}</h3><p className="text-sm text-[#756C65] mt-3 leading-relaxed">{s.description||'Servicio personalizado.'}</p>{s.price!=null&&<p className="mt-4 font-bold text-[#B96D59]">{Number(s.price).toFixed(0)} €</p>}</article>)}</div>}</section>
  <section className="bg-white border-y border-[#D98B73]/15"><div className="max-w-6xl mx-auto px-5 py-16 sm:py-20"><div className="flex items-end justify-between gap-5 mb-10"><div><p className="text-[#B96D59] text-xs font-bold uppercase tracking-[.2em]">Galería</p><h2 className="font-display text-3xl sm:text-4xl font-bold text-[#244536] mt-2">Próximamente, tus diseños</h2></div><button onClick={()=>setActiveTab('atelier')} className="text-xs font-bold uppercase tracking-widest text-[#244536] flex items-center gap-2">Atelier<ArrowRight className="w-4 h-4"/></button></div>{gallery.length===0?<div className="min-h-56 flex flex-col items-center justify-center border border-dashed border-[#D98B73]/40 rounded-xl bg-[#F7F0E8] text-center px-6"><Flower2 className="w-8 h-8 text-[#D98B73] mb-3"/><p className="font-semibold text-[#244536]">Aquí aparecerán las fotos del trabajo de Betty.</p><p className="text-sm text-[#756C65] mt-1">Las imágenes se podrán subir posteriormente desde Staff.</p></div>:<div className="grid grid-cols-2 md:grid-cols-3 gap-3 sm:gap-5">{gallery.map((g,i)=><figure key={g.id} className={'group overflow-hidden rounded-xl bg-[#F7F0E8] '+(i===0?'md:col-span-2 md:row-span-2':'')}><img src={g.photoBase64} alt={g.title||g.caption||'Diseño de BettyJaimez Blanco'} loading="lazy" className="w-full h-full min-h-48 object-cover group-hover:scale-105 transition-transform duration-500"/><figcaption className="p-3 text-sm text-[#244536]">{g.title||g.caption||'BettyJaimez Blanco'}</figcaption></figure>)}</div>}</div></section>
  <section className="bg-[#173227] text-white px-5 py-16 sm:py-20"><div className="max-w-4xl mx-auto text-center space-y-6"><GreenlantersLogo size={72} className="justify-center mx-auto"/><h2 className="font-display text-3xl sm:text-5xl font-bold">Un detalle puede cambiarlo todo.</h2><p className="text-white/75 max-w-2xl mx-auto">Nail art, color y cuidado pensados para ti.</p><div className="flex flex-col sm:flex-row justify-center gap-3"><button onClick={()=>setActiveTab('booking')} className="px-7 py-4 bg-[#F2C6B5] text-[#244536] font-bold text-xs uppercase tracking-widest rounded-lg hover:bg-white">Reservar cita</button><a href="https://www.instagram.com/bettyjaimezblanco/" target="_blank" rel="noreferrer" className="px-7 py-4 border border-white/30 rounded-lg text-xs font-bold uppercase tracking-widest hover:border-[#F2C6B5]">@bettyjaimezblanco</a></div></div></section>
 </div>
};